print("##############################")
print("#                            #")
print("#     Galih Aji Sabdaraya    #")
print("#       2310817210005        #")
print("#                            #")
print("##############################")