Nama = input("Nama                      : ")
NIM = input("NIM                       : ")
Paralel = input("Kelas Paralel             : ")
Lahir = input("Tempat/Tanggal Lahir      : ")
Alamat = input("Alamat                    : ")
Hobi = input("Hobby                     : ")
No_HP = input("No. HP                    : ")

print("\nNama                      : " + Nama)
print("NIM                       : " + NIM)
print("Kelas Paralel             : " + Paralel)
print("Tempat/Tanggal Lahir      : " + Lahir)
print("Alamat                    : " + Alamat)
print("Hobby                     : " + Hobi)
print("No. HP                    : " + No_HP)